IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'USXENT\sqldev')
CREATE LOGIN [USXENT\sqldev] FROM WINDOWS
GO
CREATE USER [USXENT\SQLDEV] FOR LOGIN [USXENT\sqldev] WITH DEFAULT_SCHEMA=[USXENT\SQLDEV]
GO
GRANT SHOWPLAN TO [USXENT\SQLDEV]
REVOKE CONNECT TO [USXENT\SQLDEV]
